export const homeBannerImgData = [
  "https://plus.unsplash.com/premium_photo-1664202526559-e21e9c0fb46a?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://plus.unsplash.com/premium_photo-1708274926468-f3ef322edffc?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1612731486606-2614b4d74921?q=80&w=2020&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1478803431644-b832801eefa7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
];

export const productsData = [
  {
    id: 1,
    img: "//www.snitch.co.in/cdn/shop/files/4369ae70e755841ff395fd1207a836fc.webp?v=1724416086",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, aliquam!",
    alt: "snitch man",
    price: 1899,
    priceDropped: 1699,
    title: "Black Textured Casual Shirt",
    category: "Shirts",
    rating: 4.5,
    stock: 12,
    details: {
      material: "Cotton",
      fit: "Slim Fit",
      color: "Black",
      sizes: ["S", "M", "L", "XL"],
      care: "Machine wash cold with like colors",
      delivery: "Free delivery within 5-7 business days.",
    },
  },
  {
    id: 2,
    img: "https://www.snitch.co.in/cdn/shop/files/6bf2ba180070301e22a1ddef61c3e3b2.webp?v=1724416618",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, aliquam!",
    alt: "snitch man",
    price: 1299,
    priceDropped: 400,
    title: "Grey Cotton Casual Shirt",
    category: "Shirts",
    rating: 4.0,
    stock: 20,
    details: {
      material: "Cotton",
      fit: "Regular Fit",
      color: "Grey",
      sizes: ["S", "M", "L"],
      care: "Hand wash recommended",
      delivery: "Free delivery within 5-7 business days.",
    },
  },
  {
    id: 3,
    img: "https://www.snitch.co.in/cdn/shop/files/9ab72a02dbd3eb956337033a5a26fbfd.webp?v=1724416086",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, aliquam!",
    alt: "snitch man",
    price: 6199,
    priceDropped: null,
    title: "Blue Checked Casual Shirt",
    category: "Shirts",
    rating: 4.8,
    stock: 5,
    details: {
      material: "Linen",
      fit: "Slim Fit",
      color: "Blue",
      sizes: ["M", "L", "XL"],
      care: "Machine wash cold, tumble dry low",
      delivery: "Free delivery within 3-5 business days.",
    },
  },
  {
    id: 4,
    img: "https://www.snitch.co.in/cdn/shop/files/2aba87d90311853e40793c5c7ba22246.webp?v=1724416057",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, aliquam!",
    alt: "snitch man",
    price: 119,
    priceDropped: null,
    title: "White Classic Casual Shirt",
    category: "Shirts",
    rating: 3.8,
    stock: 25,
    details: {
      material: "Polyester",
      fit: "Regular Fit",
      color: "White",
      sizes: ["S", "M"],
      care: "Dry clean only",
      delivery: "Standard delivery within 7-10 business days.",
    },
  },
  {
    id: 5,
    img: "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/6a16266592049062199124aca92bb8a8_b558a789-13eb-4659-998c-efeb434a88cf.webp?v=1725081068&width=600",
    desc: "Khaki Self-Design Cuban Shirt",
    alt: "snitch man",
    price: 1399,
    priceDropped: null,
    title: "Khaki Self-Design Cuban Shirt",
    category: "Shirts",
    rating: 4.2,
    stock: 15,
    details: {
      material: "Cotton Blend",
      fit: "Relaxed Fit",
      color: "Khaki",
      sizes: ["M", "L", "XL"],
      care: "Machine wash with gentle cycle",
      delivery: "Free delivery within 5-7 business days.",
    },
  },
  {
    id: 6,
    img: "https://www.snitch.co.in/cdn/shop/files/35a2807db1003b53c7fcfbc94bfb7a25.webp?v=1725080384&width=1800",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, aliquam!",
    alt: "snitch man",
    price: 1199,
    priceDropped: null,
    title: "Brown Solid Casual Shirt",
    category: "Shirts",
    rating: 4.0,
    stock: 18,
    details: {
      material: "Cotton",
      fit: "Slim Fit",
      color: "Brown",
      sizes: ["S", "M", "L"],
      care: "Machine wash cold with like colors",
      delivery: "Free delivery within 5-7 business days.",
    },
  },
  {
    id: 7,
    img: "https://www.snitch.co.in/cdn/shop/files/ecbf02346d6bde1b96ac86a2feaab218.webp?v=1724926836&width=1800",
    desc: "Blue Textured Printed Shirt",
    alt: "snitch man",
    price: 1199,
    priceDropped: null,
    title: "Blue Textured Printed Shirt",
    category: "Shirts",
    rating: 4.7,
    stock: 10,
    details: {
      material: "Cotton",
      fit: "Regular Fit",
      color: "Blue",
      sizes: ["S", "M", "L", "XL"],
      care: "Machine wash cold, tumble dry low",
      delivery: "Free delivery within 5-7 business days.",
    },
  },
  {
    id: 8,
    img: "https://www.snitch.co.in/cdn/shop/files/936d35ebd9e2424f14b9d7caaf459c63.webp?v=1724926489&width=1800",
    desc: "Teal Green Checks Oxford Shirt",
    alt: "snitch man",
    price: 1199,
    priceDropped: 900,
    title: "Teal Green Checks Oxford Shirt",
    category: "Shirts",
    rating: 4.4,
    stock: 14,
    details: {
      material: "Oxford Cloth",
      fit: "Slim Fit",
      color: "Teal Green",
      sizes: ["M", "L", "XL"],
      care: "Machine wash with gentle cycle",
      delivery: "Free delivery within 5-7 business days.",
    },
  },
];

export const productDescription = {
  Composition: "100% cotton",
  GSM: 220,
  Colour: "Black",
  "Country of production": "India",
  "Wash care": "Machine wash cold with similar colours.",
  "Only non-chlorine": true,
  "Tumble dry low": true,
  "Warm Iron if needed": true,
  Sizing: "Garment measurement in inches.",
  "Estimated order processing time": "48 hours.",
};
